### ISSUE TITLE
all: code does not build with go1.11

### ISSUE THREAD

**Issue by codyoss** [GoogleCloudPlatform/golang-samples#1602]
The main module declares a version of 1.11, but does not build with 1.11.

```bash
$ go version
go version go1.11.13 linux/amd64

$ go build ./...
# golang.org/x/exp/rand
/go/pkg/mod/golang.org/x/exp@v0.0.0-20200513190911-00229845015e/rand/rng.go:63:19: undefined: bits.Add64
/go/pkg/mod/golang.org/x/exp@v0.0.0-20200513190911-00229845015e/rand/rng.go:64:16: undefined: bits.Add64
/go/pkg/mod/golang.org/x/exp@v0.0.0-20200513190911-00229845015e/rand/rng.go:68:12: undefined: bits.Mul64
```
